version: '3.9'

services:
  app:
    container_name: app
    build: 
      context: ./docker/php
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www
  nginx:
    container_name: nginx
    build: 
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
      - db
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
