services:
  app:
    container_name: bridgin_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 5173:5173
    tty: true
    networks:
      - bridgin_network
    volumes:
      - .:/var/www/html
      - app_node_modules:/app/node_modules
      - app_vender:/app/vendor
      - ./docker/php/logs:/var/log
    extra_hosts:
      - host.docker.internal:host-gateway # windows環境でxdebugを使うために記述

  web:
    container_name: bridgin_web
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html
    tty: true
    networks:
      - bridgin_network
    depends_on:
      - app
      - db

  db:
    image: mysql:8.0
    container_name: bridgin_db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - bridgin_network
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: bridgin_redis
    ports:
      - 16379:6379
    restart: unless-stopped
    volumes:
      - ./docker/redis/data:/data
    networks:
      - bridgin_network
    tty: true

# 軽量化のため名前付きvolumesで保存
volumes:
  app_node_modules:
  app_vender:

# コンテナ間を接続
networks:
  bridgin_network:
    driver: bridge
