version: '3.9'

services:
  app:
    container_name: app
    build: 
      context: ./docker/php
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www
  nginx:
    container_name: nginx
    build: 
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
      - db
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes:
      - ./logs:/var/log/mysql
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/mysql
      - /var/log/mysql
    ports:
      - ${DB_PORT}:3306
