version: '3.9'

services:
  app:
    container_name: app
    build: 
      context: ./docker/php
      dockerfile: php.Dockerfile
    tty: true
    volumes: # 高速化のため名前付きvolumesで保存
      - .:/var/www:cached
      - app_node_modules:/app/node_modules
      - app_vender:/app/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    
  nginx:
    container_name: nginx
    build: 
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
    ports:
      - 8888:80
      - 5173:5173
    volumes:
      - .:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    tty: true
    depends_on:
      - app
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes:
      - ./logs:/var/log/mysql
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 16379:6379
    restart: unless-stopped
    volumes:
      - .docker/redis/data:/data
    tty: true

volumes: # 名前付きvolumesで保存
  app_node_modules:
  app_vender: