services:
  app:
    container_name: bridgin_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    networks:
      - bridgin_network
    volumes:
      - .:/var/www/html
      - ./docker/php/logs:/var/log
      - app_vender:/app/vendor
      - app_node_modules:/app/node_modules
    tty: true

  web:
    container_name: bridgin_web
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 9000:80
    volumes:
      - .:/var/www/html
    networks:
      - bridgin_network
    depends_on:
      - app
      - db

  db:
    image: mysql:8.0
    container_name: bridgin_db
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 13306:3306
    restart: unless-stopped
    networks:
      - bridgin_network
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: bridgin_redis
    ports:
      - 16379:6379
    restart: unless-stopped
    volumes:
      - ./docker/redis/data:/data
    networks:
      - bridgin_network

volumes:
  app_node_modules:
  app_vender:

networks:
  bridgin_network:
    driver: bridge
