<?php

namespace Database\Seeders;

use App\Models\Asset;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssetsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assets = [
            [
                'name' => 'ビットコイン',
                'amount' => 56483,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 7,
            ],
            [
                'name' => 'SBI全米',
                'amount' => 127793,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 3,
            ],
            [
                'name' => 'オルカン',
                'amount' => 1007981,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => '現金',
                'amount' => 62333,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 2,
            ],
            [
                'name' => '米ドル',
                'amount' => 11424,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 6,
            ],
            [
                'name' => '金',
                'amount' => 147227,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 8,
            ],
            [
                'name' => 'BND',
                'amount' => 277467,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'HDV',
                'amount' => 711184,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'VTI',
                'amount' => 137741,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'SPYD',
                'amount' => 612061,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => '十六',
                'amount' => 148027,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '三菱UFJ',
                'amount' => 5637784,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '住信SBI',
                'amount' => 224619,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '楽天',
                'amount' => 2943753,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'みんなの',
                'amount' => 3003,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'イオン',
                'amount' => 4,
                'registration_date' => '2023-04-29',
                'created_at' => '2023-04-29',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],

            [
                'name' => 'ビットコイン',
                'amount' => 56240,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 7,
            ],
            [
                'name' => 'SBI全米',
                'amount' => 133864,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 3,
            ],
            [
                'name' => 'オルカン',
                'amount' => 1086943,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => '現金',
                'amount' => 52028,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 2,
            ],
            [
                'name' => '米ドル',
                'amount' => 15067,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 6,
            ],
            [
                'name' => '金',
                'amount' => 150318,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 8,
            ],
            [
                'name' => 'BND',
                'amount' => 291453,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'HDV',
                'amount' => 726499,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'VTI',
                'amount' => 141269,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'SPYD',
                'amount' => 605945,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => '十六',
                'amount' => 148290,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '三菱UFJ',
                'amount' => 5721250,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '住信SBI',
                'amount' => 212541,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '楽天',
                'amount' => 2943753,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'みんなの',
                'amount' => 3003,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'イオン',
                'amount' => 4,
                'registration_date' => '2023-05-26',
                'created_at' => '2023-05-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],

            [
                'name' => 'ビットコイン',
                'amount' => 67683,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 7,
            ],
            [
                'name' => 'SBI全米',
                'amount' => 146023,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 3,
            ],
            [
                'name' => 'オルカン',
                'amount' => 1201900,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => '現金',
                'amount' => 44589,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 2,
            ],
            [
                'name' => '米ドル',
                'amount' => 28153,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 6,
            ],
            [
                'name' => '金',
                'amount' => 151887,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 8,
            ],
            [
                'name' => 'BND',
                'amount' => 312851,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'HDV',
                'amount' => 775633,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'VTI',
                'amount' => 153929,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'SPYD',
                'amount' => 645360,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => '十六',
                'amount' => 148554,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '三菱UFJ',
                'amount' => 5910831,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '住信SBI',
                'amount' => 198204,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '楽天',
                'amount' => 2943753,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'みんなの',
                'amount' => 3003,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'イオン',
                'amount' => 4,
                'registration_date' => '2023-06-25',
                'created_at' => '2023-06-25',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],

            [
                'name' => 'ビットコイン',
                'amount' => 63501,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 7,
            ],
            [
                'name' => 'SBI全米',
                'amount' => 150418,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 3,
            ],
            [
                'name' => 'オルカン',
                'amount' => 1268553,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => '現金',
                'amount' => 44589,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 2,
            ],
            [
                'name' => '米ドル',
                'amount' => 29803,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 6,
            ],
            [
                'name' => '金',
                'amount' => 152121,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 8,
            ],
            [
                'name' => 'BND',
                'amount' => 318243,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'HDV',
                'amount' => 840518,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'VTI',
                'amount' => 160143,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'SPYD',
                'amount' => 707301,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => '十六',
                'amount' => 445818,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '三菱UFJ',
                'amount' => 6370233,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '住信SBI',
                'amount' => 180755,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '楽天',
                'amount' => 2943753,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'みんなの',
                'amount' => 3003,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'イオン',
                'amount' => 4,
                'registration_date' => '2023-07-26',
                'created_at' => '2023-07-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],

            [
                'name' => 'ビットコイン',
                'amount' => 58540,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 7,
            ],
            [
                'name' => 'SBI全米',
                'amount' => 149908,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 3,
            ],
            [
                'name' => 'オルカン',
                'amount' => 1293463,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => '現金',
                'amount' => 31981,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 2,
            ],
            [
                'name' => '米ドル',
                'amount' => 33174,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 6,
            ],
            [
                'name' => '金',
                'amount' => 153851,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 8,
            ],
            [
                'name' => 'BND',
                'amount' => 332383,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'HDV',
                'amount' => 881187,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'VTI',
                'amount' => 159690,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'SPYD',
                'amount' => 706465,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => '十六',
                'amount' => 149194,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '三菱UFJ',
                'amount' => 6402207,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '住信SBI',
                'amount' => 138025,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '楽天',
                'amount' => 2943753,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'みんなの',
                'amount' => 3007,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'イオン',
                'amount' => 4,
                'registration_date' => '2023-08-26',
                'created_at' => '2023-08-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],

            [
                'name' => 'ビットコイン',
                'amount' => 60327,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 7,
            ],
            [
                'name' => 'SBI全米',
                'amount' => 149173,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 3,
            ],
            [
                'name' => 'オルカン',
                'amount' => 1322063,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => '現金',
                'amount' => 31981,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 2,
            ],
            [
                'name' => '米ドル',
                'amount' => 13743,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 6,
            ],
            [
                'name' => '金',
                'amount' => 157171,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 8,
            ],
            [
                'name' => 'BND',
                'amount' => 344338,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'HDV',
                'amount' => 887503,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'VTI',
                'amount' => 158168,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'SPYD',
                'amount' => 708027,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => '十六',
                'amount' => 149194,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '三菱UFJ',
                'amount' => 6462127,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '住信SBI',
                'amount' => 204983,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '楽天',
                'amount' => 2943753,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'みんなの',
                'amount' => 3007,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'イオン',
                'amount' => 4,
                'registration_date' => '2023-09-26',
                'created_at' => '2023-09-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],

            [
                'name' => 'ビットコイン',
                'amount' => 77741,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 7,
            ],
            [
                'name' => 'SBI全米',
                'amount' => 148901,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 3,
            ],
            [
                'name' => 'オルカン',
                'amount' => 1333563,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => '現金',
                'amount' => 33349,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 2,
            ],
            [
                'name' => '米ドル',
                'amount' => 33174,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 6,
            ],
            [
                'name' => '金',
                'amount' => 162760,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 8,
            ],
            [
                'name' => 'BND',
                'amount' => 350169,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'HDV',
                'amount' => 884550,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'VTI',
                'amount' => 156845,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'SPYD',
                'amount' => 698033,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => '十六',
                'amount' => 149723,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '三菱UFJ',
                'amount' => 6804431,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '住信SBI',
                'amount' => 215101,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '楽天',
                'amount' => 2947940,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'みんなの',
                'amount' => 3007,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'イオン',
                'amount' => 4,
                'registration_date' => '2023-10-26',
                'created_at' => '2023-10-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],

            [
                'name' => 'ビットコイン',
                'amount' => 85751,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 7,
            ],
            [
                'name' => 'SBI全米',
                'amount' => 156863,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 3,
            ],
            [
                'name' => 'オルカン',
                'amount' => 1458578,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => '現金',
                'amount' => 31981,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 2,
            ],
            [
                'name' => '米ドル',
                'amount' => 31893,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 6,
            ],
            [
                'name' => '金',
                'amount' => 163833,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 8,
            ],
            [
                'name' => 'BND',
                'amount' => 368949,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'HDV',
                'amount' => 922353,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'VTI',
                'amount' => 167369,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => 'SPYD',
                'amount' => 920320,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 12,
            ],
            [
                'name' => '十六',
                'amount' => 149987,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '三菱UFJ',
                'amount' => 6747478,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '住信SBI',
                'amount' => 1419199,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => '楽天',
                'amount' => 2947940,
                'registration_date' => '2023-11-26',
                'created_at' => '2023-11-26',
                'updated_at' => now(),
                'user_id' => 1,
                'category_id' => 1,
            ],
        ];
        // foreach($assets as $assetData) {
        //     Asset::create([
        //         'name' => $assetData['name'],
        //         'amount' => $assetData['amount'],
        //         'registration_date' => $assetData['registration_date'],
        //         'created_at' => $assetData['created_at'],
        //         'updated_at' => $assetData['updated_at'],
        //         'user_id' => $assetData['user_id'],
        //         'category_id' => $assetData['category_id'],
        //     ]);
        // }
        DB::table('assets')->insert($assets);
    }
}
