name: Laravel Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをクローンする
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker Compose をインストールする
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Docker Compose でプロジェクトのコンテナをビルド＆起動する
      - name: Set up and run Docker Compose
        run: |
          cp .env.testing .env
          docker-compose up -d --build
          docker-compose exec app composer install --prefer-dist --no-progress --no-suggest --ansi
          docker-compose exec app php artisan key:generate
          docker-compose exec app php artisan migrate:refresh --seed
          docker-compose exec app npm run dev

      # コンテナ内でのテスト実行
      - name: Run tests in Docker
        run: docker-compose exec app php artisan test

      # Docker Compose で立ち上げたコンテナの停止・削除
      - name: Tear down Docker Compose
        run: docker-compose down
